#!/usr/bin/env python3
"""Linux/KDE layer popup viewer — PyQt6 + QWebEngineView.

Opens output/layout.html (generated by tools/gen-layout-html.py) in a
fullscreen Qt window. Escape closes the window.

Runtime deps (Fedora):
  dnf install python3-pyqt6 python3-pyqt6-webengine
"""

import sys
import pathlib

from PyQt6.QtWidgets import QApplication, QMainWindow
from PyQt6.QtWebEngineWidgets import QWebEngineView
from PyQt6.QtWebEngineCore import QWebEngineProfile, QWebEnginePage
from PyQt6.QtCore import Qt, QUrl
from PyQt6.QtGui import QShortcut, QKeySequence

ROOT = pathlib.Path(__file__).resolve().parent.parent
HTML = ROOT / "output" / "layout.html"


class LayerWindow(QMainWindow):
    def __init__(self, url):
        super().__init__()
        self.setWindowTitle("Keyboard Layers")
        # Named profile persists localStorage across sessions (~/.local/share/QtWebEngine/go60-layout/)
        profile = QWebEngineProfile("go60-layout", self)
        page = QWebEnginePage(profile, self)
        view = QWebEngineView(self)
        view.setPage(page)
        view.load(url)
        self.setCentralWidget(view)
        # QShortcut works at the window level — keyPressEvent won't fire because
        # the Chromium render widget inside QWebEngineView consumes key events first.
        QShortcut(QKeySequence("Escape"), self).activated.connect(self.close)
        screen = QApplication.primaryScreen().availableGeometry()
        w, h = int(screen.width() * 0.6), int(screen.height() * 0.8)
        self.resize(w, h)
        self.move(screen.center() - self.rect().center())
        self.show()


def main():
    if not HTML.exists():
        print(f"error: {HTML} not found — run 'make html' first", file=sys.stderr)
        sys.exit(1)

    app = QApplication(sys.argv)
    window = LayerWindow(QUrl.fromLocalFile(str(HTML)))
    sys.exit(app.exec())


if __name__ == "__main__":
    main()
